// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Dictionaries.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Dictionary
    {
        /// <summary>
        /// Initializes a new instance of the Dictionary class.
        /// </summary>
        public Dictionary() { }

        /// <summary>
        /// Initializes a new instance of the Dictionary class.
        /// </summary>
        public Dictionary(int? id = default(int?), string name = default(string), string version = default(string), string metadata = default(string), IList<Item> items = default(IList<Item>))
        {
            Id = id;
            Name = name;
            Version = version;
            Metadata = metadata;
            Items = items;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public string Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Metadata")]
        public string Metadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Items")]
        public IList<Item> Items { get; set; }

    }
}
